# Unique name for this workflow
name: ScratchOrg Creation

# Definition when the workflow should run

on:
  workflow_dispatch:
    inputs:
     scratch-org_name:
      #friendly name to the scratch-org which needs to be created
      default: 'scratch-org'
      required: true

# Jobs to be executed

jobs:

 environment-setup:
 
    name: environment-setup
    runs-on: ubuntu-latest
   
    steps:
   
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v2
       
      # Cache node_modules to speed up the process
      - name: Setup Node Environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
         
 validate:
    name: ScratchOrg Creation
    needs: [environment-setup]
    runs-on: ubuntu-latest
    # if: github.event == 'push'
    steps:
   
    # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
              wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
              sudo mkdir ~/sfdx-cli
              sudo tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx-cli --strip-components 1
              export PATH=$PATH:~/sfdx-cli/bin
              echo "~/sfdx-cli/bin" >> $GITHUB_PATH
              sudo chmod -R 777 ~/sfdx-cli
              sfdx --version
           
    # Run Salesforce CLI Scanner For Security checks
      - name: 'Check for SFDX Update'
        run: sfdx update
       
    # Install Salesforce CLI Scanner
      - name: 'Install Salesforce CLI Scanner'
        run: sfdx plugins:install @salesforce/sfdx-scanner

    # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v2

    # Connect with Salesforce ORG
      - name: 'Connect with Salesforce ORG'
        working-directory: .github/jwt/
        run: sfdx auth:jwt:grant --clientid ${{ secrets.DEVHUBCONSUMERKEY }} --jwtkeyfile server.key --username ${{ secrets.DEVHUBUSERNAME}} -d --instanceurl ${{ secrets.DEVHUBINSTANCEURL }}
       
     # Run Salesforce CLI Scanner For Security checks _
      - name: 'List All ORGS'
        run: sfdx force:org:list
     
      - name: 'Create Scratch Org Definition File'
        run: |
          mkdir -p config
          echo '{
            "orgName": "My Scratch Org",
            "edition": "Developer",
            "namespace": "RhythmTest",
            "features": [],
            "settings": {
              "lightningExperienceSettings": {
                "enableS1DesktopEnabled": true
              },
              "mobileSettings": {
                "enableS1EncryptedStoragePref2": false
              }
            }
          }' > config/project-scratch-def.json
 
      # Create scratch org
      - name: 'Create scratch org'
        run: |
             echo 'y' | sfdx sf org create scratch --target-dev-hub ${{ secrets.DEVHUBUSERNAME }} --definition-file config/project-scratch-def.json --alias myscratchorg --set-default --duration-days 30 --name ${{github.event.inputs.scratch-org_name}}
       
      # Generate scratch org User and password        
      - name: Change password
        run: sfdx org generate password --target-org myscratchorg
                                   
      - name: Display user information
        id: display_user
        run: sfdx org display user --target-org myscratchorg
       
